#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=90
INTERFACE=br-lan
PORT=1337

# check if configuration exists
[ -e "/etc/Socks5.conf" ] || exit 0

iptable_start() {
    /bin/echo -n "running Socks5 iptables ..."

    # Run iptable commands
    iptables -t nat -N Socks5

    iptables -t nat -A Socks5 -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A Socks5 -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A Socks5 -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A Socks5 -d 169.254.0.0/16 -j RETURN
#    iptables -t nat -A Socks5 -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A Socks5 -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A Socks5 -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A Socks5 -d 240.0.0.0/4 -j RETURN

    iptables -t nat -A Socks5 -p tcp -j REDIRECT --to-ports ${PORT}

    iptables -t nat -A PREROUTING -i ${INTERFACE} -p tcp -j Socks5

    iptables -A INPUT -i br-lan -p tcp --dport ${PORT} -j ACCEPT

    /bin/echo " done"
}

iptable_stop() {
    /bin/echo -n "cleaning Socks5 iptables ..."

    # Run iptable commands
    iptables -t nat -F Socks5
    iptables -t nat -F PREROUTING
    iptables -t nat -F POSTROUTING
    iptables -F INPUT
    iptables -F FORWARD
    iptables -t nat -X Socks5

    /bin/echo " done"
}

start() {
    if [ -e "/var/run/Socks5.pid" ]; then
        echo "Socks5 is already running"
        exit 0
    fi

    /bin/echo -n "running Socks5 ..."

    # startup the safety-wrapper for the daemon
    /usr/sbin/redsocks -c /etc/Socks5.conf -p /var/run/Socks5.pid

    /bin/echo " done"
    iptable_start
}


stop() {
    if [ ! -e "/var/run/Socks5.pid" ]; then
        echo "Socks5 is not running"
        exit 0
    fi

    /bin/echo -n "stopping Socks5 ..."

    # kill the process
    /bin/kill $(cat /var/run/Socks5.pid)
    rm /var/run/Socks5.pid

    echo " done"
    iptable_stop

    /bin/echo -n "restarting firewall ..."
    /etc/init.d/firewall restart &> /dev/null
    /bin/echo " done"
}
